INSERT INTO USER (ID, NAME, PASSWORD)
VALUES (0, 'root', 'root');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (-1, 0, '/static/img/sourceTree/unknow.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (0, 0, '/static/img/sourceTree/network.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (0, 1, '/static/img/sourceTree/config_large.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (2, 0, '/static/img/sourceTree/cloud_16x16.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (2, 1, '/static/img/sourceTree/system_256x256.ico');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (3, 0, '/static/img/sourceTree/machine_16x16.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (3, 1, '/static/img/sourceTree/machine_128x128.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (3, 2, '/static/img/sourceTree/machine_off_16x16.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (4, 0, '/static/img/sourceTree/component.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (4, 1, '/static/img/sourceTree/component_128x128.ico');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (5, 0, '/static/img/sourceTree/fx_16x16.png');

INSERT INTO SOURCE_TYPE_ICON(SOURCETYPEID, FEATURE, URL)
VALUES (5, 1, '/static/img/sourceTree/fx_256x256.ico');