BEGIN TRANSACTION;
INSERT INTO USER (ID, NAME, PASSWORD) VALUES (0, 'root', 'root');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (0, 0, '/static/img/sourceTree/network.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (1, 0, '/static/img/sourceTree/cloud_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (1, 1, '/static/img/sourceTree/system_256x256.ico');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (2, 0, '/static/img/sourceTree/hardware_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (2, 1, '/static/img/sourceTree/hardware_256x256.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (3, 0, '/static/img/sourceTree/software_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (3, 1, '/static/img/sourceTree/software_128x128.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (4, 0, '/static/img/sourceTree/machine_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (4, 1, '/static/img/sourceTree/machine_128x128.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (4, 2, '/static/img/sourceTree/machine_off_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (5, 0, '/static/img/sourceTree/component.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (5, 1, '/static/img/sourceTree/component_128x128.ico');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (6, 0, '/static/img/sourceTree/fx_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (6, 1, '/static/img/sourceTree/fx_256x256.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (7, 0, '/static/img/sourceTree/process_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (7, 1, '/static/img/sourceTree/process_128x128.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (8, 0, '/static/img/sourceTree/log_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (8, 1, '/static/img/sourceTree/log_128x128.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (9, 0, '/static/img/sourceTree/var_16x16.png');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (9, 1, '/static/img/sourceTree/var_128x128.ico');
INSERT INTO SOURCE_ICON(SOURCEID, FEATURE, URL) VALUES (10, 0, 'null');
COMMIT;